// <auto-generated />
using System;
using KykCamasirhaneRandevu.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KykCamasirhaneRandevu.Migrations
{
    [DbContext(typeof(KykContext))]
    [Migration("20250419144338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Anket", b =>
                {
                    b.Property<int>("AnketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnketId"));

                    b.Property<int>("ArayuzPuani")
                        .HasColumnType("int");

                    b.Property<int>("GenelMemnuniyetPuani")
                        .HasColumnType("int");

                    b.Property<int>("GirisKolayligiPuani")
                        .HasColumnType("int");

                    b.Property<int>("OneriPuani")
                        .HasColumnType("int");

                    b.Property<int>("PerformansPuani")
                        .HasColumnType("int");

                    b.Property<int>("RandevuIslemiPuani")
                        .HasColumnType("int");

                    b.HasKey("AnketId");

                    b.ToTable("Anketler");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Duyuru", b =>
                {
                    b.Property<int>("DuyuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DuyuruID"));

                    b.Property<string>("DuyuruKonu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DuyuruMetin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DuyuruID");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Mesaj", b =>
                {
                    b.Property<int>("MesajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesajID"));

                    b.Property<bool>("Cevaplandi")
                        .HasColumnType("bit");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MesajIcerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciAdSoyad")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("OgrenciEposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MesajID");

                    b.ToTable("Mesajlar");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"));

                    b.Property<bool>("CezaDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_YatakNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OgrenciAdSoyad")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("OgrenciEposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OgrenciSifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OgrenciTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("RandevuID")
                        .HasColumnType("int");

                    b.HasKey("OgrenciID");

                    b.HasIndex("RandevuID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"));

                    b.Property<bool>("KurutmaSecenegi")
                        .HasColumnType("bit");

                    b.Property<byte>("MakineNo")
                        .HasColumnType("tinyint");

                    b.Property<bool>("RandevuGerceklesmeDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RandevuGunSaat")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RandevuOnayDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("RandevuSahibi")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("TeslimeKalanSure")
                        .HasColumnType("int");

                    b.HasKey("RandevuID");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Yonetici", b =>
                {
                    b.Property<int>("YoneticiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YoneticiID"));

                    b.Property<string>("YoneticiAdSoyad")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("YoneticiEposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YoneticiSifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YoneticiTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("YoneticiID");

                    b.ToTable("Yoneticiler");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Ogrenci", b =>
                {
                    b.HasOne("KykCamasirhaneRandevu.DAL.Entities.Randevu", "Randevu")
                        .WithMany()
                        .HasForeignKey("RandevuID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Randevu");
                });
#pragma warning restore 612, 618
        }
    }
}
