// <auto-generated />
using System;
using KykCamasirhaneRandevu.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KykCamasirhaneRandevu.Migrations
{
    [DbContext(typeof(KykContext))]
    [Migration("20250508171628_ayarlar")]
    partial class ayarlar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Anket", b =>
                {
                    b.Property<int>("AnketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnketId"));

                    b.Property<DateTime>("AnketTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArayuzPuani")
                        .HasColumnType("int");

                    b.Property<int>("GenelMemnuniyetPuani")
                        .HasColumnType("int");

                    b.Property<int>("GirisKolayligiPuani")
                        .HasColumnType("int");

                    b.Property<int>("OneriPuani")
                        .HasColumnType("int");

                    b.Property<int>("PerformansPuani")
                        .HasColumnType("int");

                    b.Property<int>("RandevuIslemiPuani")
                        .HasColumnType("int");

                    b.HasKey("AnketId");

                    b.ToTable("Anketler", (string)null);
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.CezaSuresi", b =>
                {
                    b.Property<int>("CezaSuresiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CezaSuresiID"));

                    b.Property<int>("CezaSuresiDakika")
                        .HasColumnType("int");

                    b.HasKey("CezaSuresiID");

                    b.ToTable("CezaSuresi");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Duyuru", b =>
                {
                    b.Property<int>("DuyuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DuyuruID"));

                    b.Property<string>("DuyuruKonu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DuyuruMetin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuyuruTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DuyuruID");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.EmailAyarlari", b =>
                {
                    b.Property<int>("EmailAyarlariID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailAyarlariID"));

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SonGuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("EmailAyarlariID");

                    b.ToTable("EmailAyarlari");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Mesaj", b =>
                {
                    b.Property<int>("MesajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesajID"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OgrenciID")
                        .HasColumnType("int");

                    b.Property<bool>("Okundu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("MesajID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("Mesajlar");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"));

                    b.Property<DateTime?>("CezaBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CezaDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_YatakNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OgrenciAdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OgrenciEposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OgrenciSifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OgrenciTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("OgrenciID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"));

                    b.Property<bool>("HatirlatmaGonderildi")
                        .HasColumnType("bit");

                    b.Property<bool>("Kurutma")
                        .HasColumnType("bit");

                    b.Property<int>("MakineNo")
                        .HasColumnType("int");

                    b.Property<int?>("OgrenciID")
                        .HasColumnType("int");

                    b.Property<bool?>("RandevuGerceklesti")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeslimeKalanSure")
                        .HasColumnType("int");

                    b.HasKey("RandevuID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.RandevuHatirlatma", b =>
                {
                    b.Property<int>("RandevuHatirlatmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuHatirlatmaID"));

                    b.Property<int>("HatirlatmaSuresiDakika")
                        .HasColumnType("int");

                    b.Property<DateTime>("SonGuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuHatirlatmaID");

                    b.ToTable("RandevuHatirlatma");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Yonetici", b =>
                {
                    b.Property<int>("YoneticiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YoneticiID"));

                    b.Property<int>("VarsayilanCezaSuresiDakika")
                        .HasColumnType("int");

                    b.Property<string>("YoneticiAdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YoneticiEposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YoneticiSifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YoneticiTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("YoneticiID");

                    b.ToTable("Yoneticiler");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Mesaj", b =>
                {
                    b.HasOne("KykCamasirhaneRandevu.DAL.Entities.Ogrenci", "Ogrenci")
                        .WithMany("Mesajlar")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Randevu", b =>
                {
                    b.HasOne("KykCamasirhaneRandevu.DAL.Entities.Ogrenci", "Ogrenci")
                        .WithMany("Randevular")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("KykCamasirhaneRandevu.DAL.Entities.Ogrenci", b =>
                {
                    b.Navigation("Mesajlar");

                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
